### ISSUE TITLE
run.py issue

### ISSUE THREAD

**Issue by msinghal95** [phage-nz/ph0neutria#25]
Hi, I was trying to run the "run.py" file, but i am getting this error
root@ubuntu:/opt/ph0neutria# sudo -H -u spider python3 run.py
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from core.core_utils import start_core
  File "/opt/ph0neutria/core/core_utils.py", line 3, in <module>
    from .config_utils import get_base_config
  File "/opt/ph0neutria/core/config_utils.py", line 3, in <module>
    from ConfigParser import SafeConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

Can you help me with this?
--

**Comment by phage-nz** [comment]
"ConfigParser" does not exist in Python 3.x, hence why if you actually look at the current config_utils.py in this repo you'll see it imported as "configparser". It appears you're not using the latest code base. Please do a fresh git pull, re-apply your custom configuration values and try again.

**Comment by msinghal95** [comment]
I did the pull reques and made appropriate to the config files, when i ran it gave me this error: 
root@ubuntu:/opt/ph0neutria# sudo -H -u spider python3 run.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'Core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from core.core_utils import start_core
  File "/opt/ph0neutria/core/core_utils.py", line 5, in <module>
    from .malware_utils import get_malware_urls, queue_malware_list
  File "/opt/ph0neutria/core/malware_utils.py", line 4, in <module>
    from .file_utils import profile_url_file, clean_up
  File "/opt/ph0neutria/core/file_utils.py", line 4, in <module>
    from .crypto_utils import hash_file, random_string
  File "/opt/ph0neutria/core/crypto_utils.py", line 16, in <module>
    BASECONFIG = get_base_config(ROOTDIR)
  File "/opt/ph0neutria/core/config_utils.py", line 127, in get_base_config
    user_agent = parser.get('Core', 'useragent')
  File "/usr/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'Core'

I am not sure what to do, please help
